Repository canonical/mysql-operator, pull requests merged in 2025-03, with the labels that each got.

#615 [DPE-6488] Address slow mysqld start upon unit reboot
  lib/charms/mysql/v0/async_replication.py
  lib/charms/mysql/v0/mysql.py
  lib/charms/mysql/v0/tls.py
  src/charm.py
  src/flush_mysql_logs.py
  src/hostname_resolution.py
  src/mysql_vm_helpers.py
  src/relations/db_router.py
  src/relations/mysql.py
  src/relations/mysql_provider.py
  src/relations/shared_db.py
  tests/integration/helpers.py
  tests/integration/high_availability/test_upgrade_rollback_incompat.py
  tests/unit/test_async_replication.py
  tests/unit/test_charm.py
  tests/unit/test_database.py
  tests/unit/test_mysql.py
Labels: bug, Libraries: Out of sync

#621 DPE-6487 PITR
  actions.yaml
  lib/charms/mysql/v0/backups.py
  lib/charms/mysql/v0/mysql.py
  lib/charms/mysql/v0/s3_helpers.py
  src/charm.py
  src/constants.py
  src/mysql_vm_helpers.py
  src/upgrade.py
  tests/integration/backups.py
  tests/integration/conftest.py
  tests/integration/helpers.py
  tests/integration/high_availability/test_upgrade_rollback_incompat.py
  tests/integration/test_backup_aws.py
  tests/integration/test_backup_ceph.py
  tests/integration/test_backup_gcp.py
  tests/integration/test_backup_pitr_aws.py
  tests/integration/test_backup_pitr_gcp.py
  tests/spread/test_backup_pitr_aws.py/task.yaml
  tests/spread/test_backup_pitr_gcp.py/task.yaml
  tests/unit/test_backups.py
  tests/unit/test_charm.py
  tests/unit/test_mysql.py
  tests/unit/test_mysqlsh_helpers.py
Labels: enhancement, Libraries: Out of sync

#416 DPE-3830 - Paxos single leader
  lib/charms/mysql/v0/mysql.py
  tests/unit/test_mysql.py
  tests/unit/test_mysqlsh_helpers.py
Labels: enhancement, Libraries: Out of sync

#634 [MISC] Ignore paths on GHA workflows
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
Labels: not bug or enhancement, Libraries: Out of sync
