Repository canonical/mysql-operator, pull requests merged in 2025-02, with the labels that each got.

#616 [DPE-6653] Signal outdated charm libs with a label
  .github/workflows/check_libs.yaml
  .github/workflows/ci.yaml
Labels: not bug or enhancement, Libraries: Out of sync

#617 feat: dpe-6306 Static code analysis
  .github/actionlint.yaml
  .github/workflows/tiobe_scan.yaml
Labels: not bug or enhancement, Libraries: Out of sync

#619 [DPE-6666] Remove async-replication test workaround
  tests/integration/high_availability/test_async_replication.py
Labels: bug, Libraries: Out of sync

#622 [DPE-6651] Update snap revisions to new builds with updated percona packages
  snap_revisions.json
Labels: enhancement, Libraries: Out of sync

#624 fix: dpe-6695 fix race on legacy mysql
  src/relations/mysql.py
Labels: bug, Libraries: Out of sync

#625 [DPE-1531] Port changes from K8s PR to avoid --initialize-insecure
  lib/charms/mysql/v0/mysql.py
  src/mysql_vm_helpers.py
Labels: not bug or enhancement, Libraries: Out of sync

#627 Avoid using incompatible juju debug-log options in test helper
  tests/integration/helpers.py
Labels: not bug or enhancement, Libraries: Out of sync
